/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as BranchRouteImport } from './routes/branch'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AdminAuditLogsRouteImport } from './routes/admin.audit-logs'
import { Route as AdminCustomersRouteImport } from './routes/admin.customers'
import { Route as AdminDashboardRouteImport } from './routes/admin.dashboard'
import { Route as AdminProductsRouteImport } from './routes/admin.products'
import { Route as AdminReportsRouteImport } from './routes/admin.reports'
import { Route as AdminSettingsRouteImport } from './routes/admin.settings'
import { Route as AdminUsersRouteImport } from './routes/admin.users'
import { Route as BranchCustomersRouteImport } from './routes/branch.customers'
import { Route as BranchDashboardRouteImport } from './routes/branch.dashboard'
import { Route as BranchExpensesRouteImport } from './routes/branch.expenses'
import { Route as BranchInventoryRouteImport } from './routes/branch.inventory'
import { Route as BranchPosRouteImport } from './routes/branch.pos'
import { Route as BranchPurchasesRouteImport } from './routes/branch.purchases'
import { Route as BranchReportsRouteImport } from './routes/branch.reports'
import { Route as BranchSalesRouteImport } from './routes/branch.sales'
import { Route as BranchSettingsRouteImport } from './routes/branch.settings'
import { Route as BranchStaffRouteImport } from './routes/branch.staff'
import { Route as BranchSuppliersRouteImport } from './routes/branch.suppliers'
import { Route as AdminBranchesIndexRouteImport } from './routes/admin.branches.index'
import { Route as AdminBranchesIdRouteImport } from './routes/admin.branches.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const BranchRoute = BranchRouteImport.update({
  id: '/branch',
  path: '/branch',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminAuditLogsRoute = AdminAuditLogsRouteImport.update({
  id: '/audit-logs',
  path: '/audit-logs',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCustomersRoute = AdminCustomersRouteImport.update({
  id: '/customers',
  path: '/customers',
  getParentRoute: () => AdminRoute,
} as any)
const AdminDashboardRoute = AdminDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AdminRoute,
} as any)
const AdminProductsRoute = AdminProductsRouteImport.update({
  id: '/products',
  path: '/products',
  getParentRoute: () => AdminRoute,
} as any)
const AdminReportsRoute = AdminReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSettingsRoute = AdminSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AdminRoute,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AdminRoute,
} as any)
const BranchCustomersRoute = BranchCustomersRouteImport.update({
  id: '/customers',
  path: '/customers',
  getParentRoute: () => BranchRoute,
} as any)
const BranchDashboardRoute = BranchDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => BranchRoute,
} as any)
const BranchExpensesRoute = BranchExpensesRouteImport.update({
  id: '/expenses',
  path: '/expenses',
  getParentRoute: () => BranchRoute,
} as any)
const BranchInventoryRoute = BranchInventoryRouteImport.update({
  id: '/inventory',
  path: '/inventory',
  getParentRoute: () => BranchRoute,
} as any)
const BranchPosRoute = BranchPosRouteImport.update({
  id: '/pos',
  path: '/pos',
  getParentRoute: () => BranchRoute,
} as any)
const BranchPurchasesRoute = BranchPurchasesRouteImport.update({
  id: '/purchases',
  path: '/purchases',
  getParentRoute: () => BranchRoute,
} as any)
const BranchReportsRoute = BranchReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => BranchRoute,
} as any)
const BranchSalesRoute = BranchSalesRouteImport.update({
  id: '/sales',
  path: '/sales',
  getParentRoute: () => BranchRoute,
} as any)
const BranchSettingsRoute = BranchSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => BranchRoute,
} as any)
const BranchStaffRoute = BranchStaffRouteImport.update({
  id: '/staff',
  path: '/staff',
  getParentRoute: () => BranchRoute,
} as any)
const BranchSuppliersRoute = BranchSuppliersRouteImport.update({
  id: '/suppliers',
  path: '/suppliers',
  getParentRoute: () => BranchRoute,
} as any)
const AdminBranchesIndexRoute = AdminBranchesIndexRouteImport.update({
  id: '/branches/',
  path: '/branches/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminBranchesIdRoute = AdminBranchesIdRouteImport.update({
  id: '/branches/$id',
  path: '/branches/$id',
  getParentRoute: () => AdminRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/branch': typeof BranchRouteWithChildren
  '/login': typeof LoginRoute
  '/admin/audit-logs': typeof AdminAuditLogsRoute
  '/admin/customers': typeof AdminCustomersRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/products': typeof AdminProductsRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/users': typeof AdminUsersRoute
  '/branch/customers': typeof BranchCustomersRoute
  '/branch/dashboard': typeof BranchDashboardRoute
  '/branch/expenses': typeof BranchExpensesRoute
  '/branch/inventory': typeof BranchInventoryRoute
  '/branch/pos': typeof BranchPosRoute
  '/branch/purchases': typeof BranchPurchasesRoute
  '/branch/reports': typeof BranchReportsRoute
  '/branch/sales': typeof BranchSalesRoute
  '/branch/settings': typeof BranchSettingsRoute
  '/branch/staff': typeof BranchStaffRoute
  '/branch/suppliers': typeof BranchSuppliersRoute
  '/admin/branches/$id': typeof AdminBranchesIdRoute
  '/admin/branches/': typeof AdminBranchesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/branch': typeof BranchRouteWithChildren
  '/login': typeof LoginRoute
  '/admin/audit-logs': typeof AdminAuditLogsRoute
  '/admin/customers': typeof AdminCustomersRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/products': typeof AdminProductsRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/users': typeof AdminUsersRoute
  '/branch/customers': typeof BranchCustomersRoute
  '/branch/dashboard': typeof BranchDashboardRoute
  '/branch/expenses': typeof BranchExpensesRoute
  '/branch/inventory': typeof BranchInventoryRoute
  '/branch/pos': typeof BranchPosRoute
  '/branch/purchases': typeof BranchPurchasesRoute
  '/branch/reports': typeof BranchReportsRoute
  '/branch/sales': typeof BranchSalesRoute
  '/branch/settings': typeof BranchSettingsRoute
  '/branch/staff': typeof BranchStaffRoute
  '/branch/suppliers': typeof BranchSuppliersRoute
  '/admin/branches/$id': typeof AdminBranchesIdRoute
  '/admin/branches': typeof AdminBranchesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/branch': typeof BranchRouteWithChildren
  '/login': typeof LoginRoute
  '/admin/audit-logs': typeof AdminAuditLogsRoute
  '/admin/customers': typeof AdminCustomersRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/products': typeof AdminProductsRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/users': typeof AdminUsersRoute
  '/branch/customers': typeof BranchCustomersRoute
  '/branch/dashboard': typeof BranchDashboardRoute
  '/branch/expenses': typeof BranchExpensesRoute
  '/branch/inventory': typeof BranchInventoryRoute
  '/branch/pos': typeof BranchPosRoute
  '/branch/purchases': typeof BranchPurchasesRoute
  '/branch/reports': typeof BranchReportsRoute
  '/branch/sales': typeof BranchSalesRoute
  '/branch/settings': typeof BranchSettingsRoute
  '/branch/staff': typeof BranchStaffRoute
  '/branch/suppliers': typeof BranchSuppliersRoute
  '/admin/branches/$id': typeof AdminBranchesIdRoute
  '/admin/branches/': typeof AdminBranchesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/branch'
    | '/login'
    | '/admin/audit-logs'
    | '/admin/customers'
    | '/admin/dashboard'
    | '/admin/products'
    | '/admin/reports'
    | '/admin/settings'
    | '/admin/users'
    | '/branch/customers'
    | '/branch/dashboard'
    | '/branch/expenses'
    | '/branch/inventory'
    | '/branch/pos'
    | '/branch/purchases'
    | '/branch/reports'
    | '/branch/sales'
    | '/branch/settings'
    | '/branch/staff'
    | '/branch/suppliers'
    | '/admin/branches/$id'
    | '/admin/branches/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/branch'
    | '/login'
    | '/admin/audit-logs'
    | '/admin/customers'
    | '/admin/dashboard'
    | '/admin/products'
    | '/admin/reports'
    | '/admin/settings'
    | '/admin/users'
    | '/branch/customers'
    | '/branch/dashboard'
    | '/branch/expenses'
    | '/branch/inventory'
    | '/branch/pos'
    | '/branch/purchases'
    | '/branch/reports'
    | '/branch/sales'
    | '/branch/settings'
    | '/branch/staff'
    | '/branch/suppliers'
    | '/admin/branches/$id'
    | '/admin/branches'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/branch'
    | '/login'
    | '/admin/audit-logs'
    | '/admin/customers'
    | '/admin/dashboard'
    | '/admin/products'
    | '/admin/reports'
    | '/admin/settings'
    | '/admin/users'
    | '/branch/customers'
    | '/branch/dashboard'
    | '/branch/expenses'
    | '/branch/inventory'
    | '/branch/pos'
    | '/branch/purchases'
    | '/branch/reports'
    | '/branch/sales'
    | '/branch/settings'
    | '/branch/staff'
    | '/branch/suppliers'
    | '/admin/branches/$id'
    | '/admin/branches/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  BranchRoute: typeof BranchRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/branch': {
      id: '/branch'
      path: '/branch'
      fullPath: '/branch'
      preLoaderRoute: typeof BranchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/audit-logs': {
      id: '/admin/audit-logs'
      path: '/audit-logs'
      fullPath: '/admin/audit-logs'
      preLoaderRoute: typeof AdminAuditLogsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/customers': {
      id: '/admin/customers'
      path: '/customers'
      fullPath: '/admin/customers'
      preLoaderRoute: typeof AdminCustomersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/dashboard': {
      id: '/admin/dashboard'
      path: '/dashboard'
      fullPath: '/admin/dashboard'
      preLoaderRoute: typeof AdminDashboardRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/products': {
      id: '/admin/products'
      path: '/products'
      fullPath: '/admin/products'
      preLoaderRoute: typeof AdminProductsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/reports': {
      id: '/admin/reports'
      path: '/reports'
      fullPath: '/admin/reports'
      preLoaderRoute: typeof AdminReportsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/settings': {
      id: '/admin/settings'
      path: '/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AdminSettingsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/branch/customers': {
      id: '/branch/customers'
      path: '/customers'
      fullPath: '/branch/customers'
      preLoaderRoute: typeof BranchCustomersRouteImport
      parentRoute: typeof BranchRoute
    }
    '/branch/dashboard': {
      id: '/branch/dashboard'
      path: '/dashboard'
      fullPath: '/branch/dashboard'
      preLoaderRoute: typeof BranchDashboardRouteImport
      parentRoute: typeof BranchRoute
    }
    '/branch/expenses': {
      id: '/branch/expenses'
      path: '/expenses'
      fullPath: '/branch/expenses'
      preLoaderRoute: typeof BranchExpensesRouteImport
      parentRoute: typeof BranchRoute
    }
    '/branch/inventory': {
      id: '/branch/inventory'
      path: '/inventory'
      fullPath: '/branch/inventory'
      preLoaderRoute: typeof BranchInventoryRouteImport
      parentRoute: typeof BranchRoute
    }
    '/branch/pos': {
      id: '/branch/pos'
      path: '/pos'
      fullPath: '/branch/pos'
      preLoaderRoute: typeof BranchPosRouteImport
      parentRoute: typeof BranchRoute
    }
    '/branch/purchases': {
      id: '/branch/purchases'
      path: '/purchases'
      fullPath: '/branch/purchases'
      preLoaderRoute: typeof BranchPurchasesRouteImport
      parentRoute: typeof BranchRoute
    }
    '/branch/reports': {
      id: '/branch/reports'
      path: '/reports'
      fullPath: '/branch/reports'
      preLoaderRoute: typeof BranchReportsRouteImport
      parentRoute: typeof BranchRoute
    }
    '/branch/sales': {
      id: '/branch/sales'
      path: '/sales'
      fullPath: '/branch/sales'
      preLoaderRoute: typeof BranchSalesRouteImport
      parentRoute: typeof BranchRoute
    }
    '/branch/settings': {
      id: '/branch/settings'
      path: '/settings'
      fullPath: '/branch/settings'
      preLoaderRoute: typeof BranchSettingsRouteImport
      parentRoute: typeof BranchRoute
    }
    '/branch/staff': {
      id: '/branch/staff'
      path: '/staff'
      fullPath: '/branch/staff'
      preLoaderRoute: typeof BranchStaffRouteImport
      parentRoute: typeof BranchRoute
    }
    '/branch/suppliers': {
      id: '/branch/suppliers'
      path: '/suppliers'
      fullPath: '/branch/suppliers'
      preLoaderRoute: typeof BranchSuppliersRouteImport
      parentRoute: typeof BranchRoute
    }
    '/admin/branches/': {
      id: '/admin/branches/'
      path: '/branches'
      fullPath: '/admin/branches/'
      preLoaderRoute: typeof AdminBranchesIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/branches/$id': {
      id: '/admin/branches/$id'
      path: '/branches/$id'
      fullPath: '/admin/branches/$id'
      preLoaderRoute: typeof AdminBranchesIdRouteImport
      parentRoute: typeof AdminRoute
    }
  }
}

interface AdminRouteChildren {
  AdminAuditLogsRoute: typeof AdminAuditLogsRoute
  AdminCustomersRoute: typeof AdminCustomersRoute
  AdminDashboardRoute: typeof AdminDashboardRoute
  AdminProductsRoute: typeof AdminProductsRoute
  AdminReportsRoute: typeof AdminReportsRoute
  AdminSettingsRoute: typeof AdminSettingsRoute
  AdminUsersRoute: typeof AdminUsersRoute
  AdminBranchesIdRoute: typeof AdminBranchesIdRoute
  AdminBranchesIndexRoute: typeof AdminBranchesIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminAuditLogsRoute: AdminAuditLogsRoute,
  AdminCustomersRoute: AdminCustomersRoute,
  AdminDashboardRoute: AdminDashboardRoute,
  AdminProductsRoute: AdminProductsRoute,
  AdminReportsRoute: AdminReportsRoute,
  AdminSettingsRoute: AdminSettingsRoute,
  AdminUsersRoute: AdminUsersRoute,
  AdminBranchesIdRoute: AdminBranchesIdRoute,
  AdminBranchesIndexRoute: AdminBranchesIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface BranchRouteChildren {
  BranchCustomersRoute: typeof BranchCustomersRoute
  BranchDashboardRoute: typeof BranchDashboardRoute
  BranchExpensesRoute: typeof BranchExpensesRoute
  BranchInventoryRoute: typeof BranchInventoryRoute
  BranchPosRoute: typeof BranchPosRoute
  BranchPurchasesRoute: typeof BranchPurchasesRoute
  BranchReportsRoute: typeof BranchReportsRoute
  BranchSalesRoute: typeof BranchSalesRoute
  BranchSettingsRoute: typeof BranchSettingsRoute
  BranchStaffRoute: typeof BranchStaffRoute
  BranchSuppliersRoute: typeof BranchSuppliersRoute
}

const BranchRouteChildren: BranchRouteChildren = {
  BranchCustomersRoute: BranchCustomersRoute,
  BranchDashboardRoute: BranchDashboardRoute,
  BranchExpensesRoute: BranchExpensesRoute,
  BranchInventoryRoute: BranchInventoryRoute,
  BranchPosRoute: BranchPosRoute,
  BranchPurchasesRoute: BranchPurchasesRoute,
  BranchReportsRoute: BranchReportsRoute,
  BranchSalesRoute: BranchSalesRoute,
  BranchSettingsRoute: BranchSettingsRoute,
  BranchStaffRoute: BranchStaffRoute,
  BranchSuppliersRoute: BranchSuppliersRoute,
}

const BranchRouteWithChildren =
  BranchRoute._addFileChildren(BranchRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  BranchRoute: BranchRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
